# Generated by Django 2.2.1 on 2019-06-14 14:56
from datetime import datetime

from django.db import migrations, models
from django.utils.timezone import make_aware


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    SpotifyUser = apps.get_model("user", "spotifyuser")
    for u in SpotifyUser.objects.all().iterator():
        u.access_token_expires_at_dt = make_aware(
            datetime.fromtimestamp(u.access_token_expires_at)
        )
        u.save()


class Migration(migrations.Migration):

    dependencies = [("users", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="spotifyuser",
            name="access_token_expires_at_dt",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Access Token Expires at"
            ),
        ),
        migrations.RunPython(forwards_func),
    ]
