# Generated by Django 2.2.1 on 2019-06-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0002_spotifyuser_access_token_expires_at_dt")]

    operations = [migrations.RemoveField(model_name="spotifyuser", name="access_token_expires_at")]
