# Generated by Django 2.2.2 on 2019-06-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20190614_1700")]

    operations = [
        migrations.AlterField(
            model_name="spotifyuser",
            name="access_token",
            field=models.CharField(editable=False, max_length=255, null=True, unique=True, verbose_name="Access Token"),
        )
    ]
