# Generated by Django 2.2.2 on 2019-06-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0005_auto_20190614_1855")]

    operations = [
        migrations.RemoveField(model_name="spotifyuser", name="display_name"),
        migrations.RemoveField(model_name="spotifyuser", name="image"),
    ]
