# Generated by Django 2.2.2 on 2019-06-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20190615_1915")]

    operations = [
        migrations.RemoveField(model_name="spotifyuser", name="last_login"),
        migrations.RemoveField(model_name="spotifyuser", name="password"),
    ]
