# Generated by Django 2.2.1 on 2019-06-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="artist", name="name"),
        migrations.RemoveField(model_name="track", name="name"),
    ]
