# Generated by Django 2.2.1 on 2019-05-11 11:06

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0003_artist_playlisttracks_track")]

    operations = [
        migrations.RemoveField(model_name="track", name="artist"),
        migrations.AlterField(
            model_name="playlisttracks",
            name="date_added",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, verbose_name="added"
            ),
        ),
    ]
