# Generated by Django 2.2.1 on 2019-05-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlists", "0005_auto_20190511_1309")]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="track",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
