# Generated by Django 2.2.1 on 2019-05-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0006_auto_20190511_1313")]

    operations = [
        migrations.AlterUniqueTogether(
            name="playlisttracks", unique_together={("playlist", "track")}
        )
    ]
