# Generated by Django 2.2.1 on 2019-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlists", "0008_trackvote")]

    operations = [
        migrations.AlterField(
            model_name="trackvote",
            name="vote",
            field=models.SmallIntegerField(
                choices=[(1, "vote +1"), (0, "vote +-0"), (-1, "vote -1")]
            ),
        )
    ]
