# Generated by Django 2.2.1 on 2019-05-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0010_auto_20190511_2210")]

    operations = [
        migrations.RenameField(
            model_name="playlisttrack", old_name="points", new_name="score"
        )
    ]
