# Generated by Django 2.2.1 on 2019-05-11 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlists", "0011_auto_20190511_2245")]

    operations = [
        migrations.AlterField(
            model_name="playlisttrack",
            name="score",
            field=models.DecimalField(
                decimal_places=7, default=1, max_digits=12, verbose_name="Points"
            ),
        )
    ]
