# Generated by Django 2.2.1 on 2019-05-15 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playlists", "0012_auto_20190512_0032"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="playlisttrack", options={"ordering": ["score"]}
        ),
        migrations.AddField(
            model_name="playlisttrack",
            name="added_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="playlisttrack",
            name="score",
            field=models.DecimalField(
                decimal_places=7, max_digits=12, verbose_name="Points"
            ),
        ),
    ]
