# Generated by Django 2.2.1 on 2019-05-15 14:34

import tagulous.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0013_auto_20190515_1342")]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="tags",
            field=tagulous.models.fields.TagField(
                _set_tag_meta=True,
                force_lowercase=True,
                help_text="Enter a comma-separated tag string",
                to="playlists.Tagulous_Playlist_tags",
            ),
        )
    ]
