# Generated by Django 2.2.1 on 2019-05-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0013_auto_20190515_1342")]

    operations = []
