# Generated by Django 2.2.1 on 2019-05-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("playlists", "0014_auto_20190515_1634")]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="spotify_id",
            field=models.CharField(
                default=123, max_length=255, unique=True, verbose_name="SpotifyID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="playlist",
            name="spotify_snapshot_id",
            field=models.CharField(
                default=321, max_length=60, verbose_name="Spotify SnapshotID"
            ),
            preserve_default=False,
        ),
    ]
