# Generated by Django 2.2.1 on 2019-05-15 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0015_auto_20190515_1730")]

    operations = [
        migrations.RemoveField(model_name="playlist", name="tags"),
        migrations.DeleteModel(name="Tagulous_Playlist_tags"),
    ]
