# Generated by Django 2.2.1 on 2019-05-15 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0016_auto_20190515_2100")]

    operations = []
