# Generated by Django 2.2.1 on 2019-05-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0017_auto_20190515_2104")]

    operations = [
        migrations.RenameModel(old_name="PlaylistTagModel", new_name="PlaylistTag")
    ]
