# Generated by Django 2.2.1 on 2019-05-15 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("playlists", "0018_auto_20190515_2108")]

    operations = [
        migrations.AlterModelOptions(
            name="playlisttag", options={"ordering": ("name",)}
        )
    ]
