---
project_name: "spotified"
domain_name: "spotified.403.io"
letsencrypt_email: "boerni@gmail.com"
app_home: "/opt/{{ project_name }}"
app_dir: "{{ app_home }}/appserver"
app_user: "spotified"
app_db_name: "spotified"
venv_dir: "{{ app_home }}/venv"
venv_python: "{{ app_home }}/venv/bin/python"
manage_py: "{{venv_python }} {{app_dir}}/manage.py"
static_dir: "{{ app_home }}/var/static"