---
- hosts: all
  remote_user: root
  tasks:
    - name: Upgrade APT to the latest packages
      apt: upgrade=safe

    - name: Install ntpdate
      apt:
        name: ntpdate
        update_cache: yes
        autoremove: yes
        autoclean: yes
        cache_valid_time: 3600

    - name: set timezone to Europe/Berlin
      timezone:
        name: Europe/Berlin

    - name: PasswordAuthentication no
      replace:
        path: "/etc/ssh/sshd_config"
        regexp: '^#?PasswordAuthentication .*$'
        replace: "PasswordAuthentication no"

    - name: Reload sshd
      systemd:
        state: reloaded
        name: ssh

  roles:
    - role: jnv.unattended-upgrades
      unattended_origins_patterns:
        - 'origin=Ubuntu,archive=${distro_codename}-security'
      unattended_remove_unused_dependencies: true
      unattended_automatic_reboot: true
      unattended_automatic_reboot_time: '03:00'
